package com.topviec.topviec_be.enums.logging;

public enum LogCategory {
    AUTH,
    CANDIDATE_PROFILE,
    CV_MANAGEMENT,
    APPLICATION,
    SAVED_JOB,
    COMPANY_FOLLOW,
    REPORTING,
    COMPANY_MANAGEMENT,
    MEMBER_MANAGEMENT,
    JOB_MANAGEMENT,
    APPLICATION_REVIEW,
    TALENT_POOL,
    INTERVIEW,
    BILLING,
    APPEAL,
    ADMIN_USER_MANAGEMENT,
    COMPANY_ADMIN,
    COMPANY_MODERATION,
    CANDIDATE_ADMIN,
    MODERATION,
    REPORT_MODERATION,
    VIOLATION_MANAGEMENT,
    SERVICE_CATALOG,
    ORDER_MANAGEMENT,
    SYSTEM_MAINTENANCE
}
